## template for server
#app:
##  host-url: http://localhost
#spring:
#  datasource:
#    url: jdbc:h2:mem:jiraTest #;INIT=RUNSCRIPT FROM 'classpath:db/changelogH2.sql';DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#    script: classpath:db/changelogH2.sql
#  liquibase:
#    enabled: false
#    drop-first: true
#    changeLog: "classpath:db/changelogH2.sql"
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: false
#    properties:
#      hibernate:
#        id:
#          new_generator_mappings: false
#        dialect: org.hibernate.dialect.H2Dialect
#        hbm2ddl:
#          auto: none
#
#logging:
#  level:
#    root: INFO
#    com:
#      Baeldung: INFO
